server:
  port: 8080
  forward-headers-strategy: native

spring:
  application:
    name: community
  datasource:
    # 실제 값은 환경 변수로 주입됨
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        default_batch_fetch_size: 100
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: WARN
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# 운영 쿠키/보안 설정
refresh:
  cookie:
    secure: true
    same-site: None
